### ISSUE TITLE
Camera Rotation.

### ISSUE THREAD

**Issue by korathias** [LifeGoal/esx_securitycam#10]
Hi, 

I have added in a few more Cameras around the map and I am struggling with something. 

{label = _U('lsecam9'), x = 381.28, y = 323.25, z = 105.57, r = {x = -25.0, y = 0.0, z = 106.57}, canRotate = true},

I can seem to rotate the Camera view when it first opens. I have edited the r = area and it only seems to twist the camera up and down and in a circle. 

Is there any way to add in h (heading), 

Thank you.

**Comment by LifeGoal** [comment]
You can add it yourself if you would like to set the heading more easy.
