### ISSUE TITLE
12 cam limit

### ISSUE THREAD

**Issue by TheRealCrappyGamer** [LifeGoal/esx_securitycam#11]
Is there a hardcoded 12 camera limit per camera group somewhere? I tried adding more cameras to the bank group and after there are more than 12, once you get to the beginning of the group or end of the group the UI crashes. I had to end up creating a new group, then change code in main.lua to support the new group to get them to work, and even then I have to keep it under 12 cameras.

Is this a limitation to Vue.js, or something I am missing in the code that is incrementing/decrementing the camera index as you scroll?

**Comment by LifeGoal** [comment]
I have no idea really as I haven't used this myself for ages. I will someday make a total rewrite of the script and fix that issue.
