### ISSUE TITLE
[Suggestion] When you leave camera view, reopen the menu?

### ISSUE THREAD

**Issue by ModoSN** [LifeGoal/esx_securitycam#2]
At the moment, when you leave the camera view... you have to walk out of the marker and back in to bring the menu up if you wanted to switch between camera locations.

I think it would be good if the menu came up when you left a camera so you could pick another location if you wanted to, and if not you could just walk away.

**Comment by LifeGoal** [comment]
Will look into it!

**Comment by LifeGoal** [comment]
Will be implemented in a future update!
