### ISSUE TITLE
Hacking works Unhacking doesnt

### ISSUE THREAD

**Issue by Psycholiquid71** [LifeGoal/esx_securitycam#9]
Seems to be on and off. It will work one min, then next min it wont. But once it stops working it doesnt work again.

Hacked the police station > changed job to police grade 3 /2 /1 > cant unhack, doesn't register me hitting E

No errors in console F8 menu

**Comment by Psycholiquid71** [comment]
Or it gets stuck in the unhack animation.

**Comment by Psycholiquid71** [comment]
Nvm I fixed it

**Comment by Psycholiquid71** [comment]
Nope still acting up, almost like when it is hacked the menus all stop working.

**Comment by LifeGoal** [comment]
Never had this issue, make a new issue with more detailed information if this is a big problem. Try to reinstall the resource correctly first and test it out.
